#!/bin/bash

pwd

make user=1 prefix=/tmp/jenkins/jobs install

make user=1 prefix=/tmp/jenkins/jobs install

export PYTHONPATH=/tmp/jenkins/jobs/PyTango:$PYTHONPATH

python ../../tests/DevTest.py pytomasz &

python ../../tests/TestSuite.py

ps -ef | awk '/DevTest.py/ {print$2}' | xargs kill -9

