/*----- PROTECTED REGION ID(PipeServerStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        PipeServerStateMachine.cpp
//
// description : State machine file for the PipeServer class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PipeServer.h>

/*----- PROTECTED REGION END -----*/	//	PipeServer::PipeServerStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace PipeServer_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//=================================================
//		pipe Allowed Methods
//=================================================
//--------------------------------------------------------
/**
 *	Method      : PipeServer::is_TestPipe_allowed()
 *	Description : Execution allowed for TestPipe pipe
 */
//--------------------------------------------------------
bool PipeServer::is_TestPipe_allowed(TANGO_UNUSED(Tango::PipeReqType type))
{
	//	Not any excluded states for TestPipe pipe in Write access.
	/*----- PROTECTED REGION ID(PipeServer::TestPipeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PipeServer::TestPipeStateAllowed_WRITE
	//	Not any excluded states for TestPipe pipe in read access.
	/*----- PROTECTED REGION ID(PipeServer::TestPipeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PipeServer::TestPipeStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(PipeServer::PipeServerStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PipeServer::PipeServerStateAllowed.AdditionalMethods

}	//	End of namespace
