.TH ITANGO "1" "September 2012" "ITango 8.0.0" "User Commands"
.SH NAME
PyTango \- manual page for ITango 8.0.0
.SH SYNOPSIS
.B usage:
\fIitango \fR[\fIIPython options\fR]
.SH "SEE ALSO"
The documentation for
.B IPython

The full documentation for
.B ITango
is maintained as a Texinfo manual.  If the
.B info
and
.B ITango
programs are properly installed at your site, the command
.IP
.B info itango
.PP
should give you access to the complete manual.
