#!/usr/bin/env python3

# ------------------------------------------------------------------------------
# This file is part of PyTango (http://www.tinyurl.com/PyTango)
#
# Copyright 2006-2012 CELLS / ALBA Synchrotron, Bellaterra, Spain
# Copyright 2013-2014 European Synchrotron Radiation Facility, Grenoble, France
#
# Distributed under the terms of the GNU Lesser General Public License,
# either version 3 of the License, or (at your option) any later version.
# See LICENSE.txt for more info.
# ------------------------------------------------------------------------------

"""The itango startup file. This executable is actually an extension of the
   ipython file that can be found in <prefix>/ipython (prefix usually being in
   linux '/usr/bin'"""

__all__ = [ "main" ]

__docformat__ = 'restructuredtext'

def main():
    import PyTango.ipython
    PyTango.ipython.run()

if __name__ == '__main__':
    main()
